### ISSUE TITLE
In some controllers it works in some it doesn't.

### ISSUE THREAD

**Issue by denisbetsi** [AddJam/ember-body-class#3]
Example: 

login.js controller
```
import Ember from 'ember';
import BodyClassMixin from 'ember-body-class/mixins/body-class';

export default Ember.Controller.extend(BodyClassMixin,{
  classNames: ["login"],
... }

```

Shows up in HTML: 
`<body class="ember-application application login">`

dashboard.js controller:

```
import Ember from 'ember';
import BodyClassMixin from 'ember-body-class/mixins/body-class';

export default Ember.Controller.extend(BodyClassMixin,{
	classNames: ["nav-md"],
.. }
```

Doesn't show up  in HTML:
`<body class="ember-application application dashboard">
`

I've tested the controller with an action to make sure those 2 are wired properly and it is. There are no errors in console.log . Any ideas?

**Comment by tradziej** [comment]
@denisbetsi: You need to add `classNames` array at Route not Controller (https://github.com/AddJam/ember-body-class#custom-classes).

In your first example it is working because `ember-body-class` adds automatically route class names: https://github.com/AddJam/ember-body-class#route-name-classes
