### ISSUE TITLE
Add Dasherized Version

### ISSUE THREAD

**Issue by thegranddesign** [AddJam/ember-body-class#4]
First off I love this addon.  I used to do something similar to this in Rails and it was a tremendous help for styling.

I have a small request.  In addition to the separate route component classes (let's say `example.com/blog/1/post/1/comments`) creating `class="blog post comments"`, I'd love it if the individual component pieces were also combined in a dasherized way.  In certain URL paths, a CSS selector of `.blog .post` could be ambiguous.

I'd rather if the above created (at the very least)

```
class="blog post comments blog-post-comments"
```

And I'd prefer a dasherized version of all paths leading up to it, so:

```
class="blog post comments blog-post blog-post-comments"
```

This allows us to be laser focused in our styles on which page the styles apply to.

Thanks for this great addon!

**Comment by chrissloey** [comment]
Hey @thegranddesign, sorry for the delay replying!

That sounds like a useful option, I don't have time to implement it myself right now but I'd be more than happy to accept a Pull Request with that as an option.

**Comment by thegranddesign** [comment]
Ok great! Would you also accept a PR to remove the monkey patching of Route (by moving all into the mixin) and switching from observers to events? The later would require a major version bump and would only be compatible with Ember 2.x.

**Comment by chrissloey** [comment]
Yep, sounds good!

**Comment by thegranddesign** [comment]
@chrissloey any chance we can get this merged?
